name: bd3lm
backbone: dit  # dit / dimamba / hf_dit
parameterization: subs
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
causal_attention: False
dropout: 0.0
ignore_bos: True
cross_attn: True
var_min: True
clip_search_delta: 0.05
clip_search_widths: []
fix_clipping: False
sampler: semi_ar
mdlm_loss_scale: False